### ISSUE TITLE
bootstrapped .travis.yml contains obsolete commands

### ISSUE THREAD

**Issue by jo** [semantic-release/cli#35]
This is a .travis.yml created by the cli:

``` yml
sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
```

I think we do not need the travis_after_all hooks anymore:

``` yml
before_script:
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
```

Also, while we're at it: add node v4 target.
